### ISSUE TITLE
Prototypes/Sample Synthetic patients not on home page

### ISSUE THREAD

**Issue by jsonin** [FluxNotes/flux#767]
The Sarcoma Patient, the tablet app, compass... 
None are listed on the fluxnotes.org home page.

How about an on-going list of prototypes + scenarios, just one-click away and located on the home page?

**Comment by mgramigna** [comment]
The ticket for this is in our current sprint and will hopefully be included in the release following this sprint.

**Comment by mgramigna** [comment]
Resolved in [v2.0.0](https://github.com/FluxNotes/flux/releases/tag/v2.0.0). Can be seen on [fluxnotes.org](https://fluxnotes.org)
